---
- name: Provision EC2 instances
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create EC2 instances
      ec2:
        region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        key_name: "{{ key_name }}"
        instance_type: "t2.micro"
        image: ""
        count: 2  # Specify the number of instances to launch
        instance_tags:
          Name: "Instance {{ item }}"
      register: ec2

    - name: Add new instances to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Print information about newly created instances
      debug:
        var: ec2.instances

